language: c

cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.conda

env:
    global:
        - NUMPY_VERSION=1.11
        - PYTHON_VERSION=3.5
        - OMP_NUM_THREADS=1

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda
    - conda create --yes -n test python=$PYTHON_VERSION
    - source activate test
    - conda install --yes numpy=$NUMPY_VERSION nose cython mpi4py scipy
    - env LD_LIBRARY_PATH=$CONDA_PREFIX/lib pip install pmesh bigfile
    - pip install abopt

install:
    - pip install .

script:
    - python runtest.py --mpirun
